#ifndef ARMV8_47_SINGLEDATATRANSFERINSTRUCTION_H
#define ARMV8_47_SINGLEDATATRANSFERINSTRUCTION_H

#include <stdint.h>

void singleDataTransfer(uint32_t instruction);

#endif //ARMV8_47_SINGLEDATATRANSFERINSTRUCTION_H