//
// Created by Vivian Lopez on 08/06/2023.
//

#ifndef ARMV8_47_SINGLEDATATRANSFERINSTRUCTION_H
#define ARMV8_47_SINGLEDATATRANSFERINSTRUCTION_H

void singleDataTransfer(uint32_t instruction);

#endif //ARMV8_47_SINGLEDATATRANSFERINSTRUCTION_H